branches:
  only:
    - develop

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - git config --global user.name "viko16"
  - git config --global user.email "16viko@gmail.com"
  - git clone --branch gh-pages ${GH_REF} dist

script:
  - npm test
  - npm run build

after_success:
  - cd dist
  - echo "ukn.me" > CNAME
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

# Note: you should set Environment Variables here or 'Settings'' on travis-ci.org
env:
  global:
    - GH_REF: https://github.com/viko16/vue-ghpages-blog.git
    # - GH_TOKEN: 'Your GitHub Personal access tokens, via https://github.com/settings/tokens'
