branches:
  only:
    - develop

language: node_js

sudo: false

node_js: stable

cache:
  directories:
  - node_modules

before_install:
- git config --global user.name "viko16"
- git config --global user.email "16viko@gmail.com"
- git clone --branch gh-pages https://github.com/viko16/vue-ghpages-blog.git dist

install:
- npm install

script:
  - npm run build

after_script:
- cd dist
- echo "ukn.me" > CNAME
- git add --all .
- git commit --message "automatically update from travis-ci"
- git push "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/viko16/vue-ghpages-blog.git
    - secure: "nLlj4UmrnpVGvvaaWC3GjW33X462Qiz6PP9LzUeXpLowS/pf1TiVIWbDPw4U3Dui+erELT8faulFW7mgCbxLW17jcBXNsnGK4lpb0/6PIRF084M26yzNNlKQjXLZh/G2GK7nVeFQdUrlwFQ5EIHYQirVX3XhDPvm8IPH1l3TCRd2AczeaEH2kGujpUKYDUyeju1ZnBFgd36IXZt4HcfKVsuDbuWfFgpQM5o+eYI0AZ5V7QcfeWzph0W3Ue/c2Qbc1SV6l3mm1bqR7hRyhxSm/2uNYYagmVET2Z/XNJ/8wbbfNK9yMFbw8ollc72tDrxZZCyET9f9EiyiAqMAYOI32LyDiPQj+hnFaUA9C/Mh6G1YYw1u9k8veg9ss2J5RdUqWiTaxjHtr50wW0xRXYokqCz7SffJoBro5gmaYle1tHPSWWM+auLmWuI/xdbyUKJreQNNfdJtFgsW57Opd89VCl1OHtqlxe3fCCeOD3B86I7jxzCa8SjtazDDpkgeeqfCZnuhpErFk/oXaedn4Urovunwpu4yMM2jP/JT8/ihf3acDTvU2vtblUWeWqe2aloZk9pnGH3uexbe4lackZZwgz8AiBtcSdQTTgV67SOx2H4ieLnwPkLYKhRO0pl4EpT/0D228OuW2vLGsMGgH/oOJTzfI4E5doGSeK7jet7OjfQ="
